version: '3'
services:
  adan:
    env_file:
      - ./.env
    image: ${DOCKER_ACCT}/adan:prfx-${CPU_TYPE}-v${IWC_INTRANET_VERSION}
    build:
      context: ./dns/docker-php-nginx
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120x
    container_name: rpoxy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
    environment:
      - "CERT_DIR=${CERT_DIR}"
      - "NGINX_VERSION=${NGINX_VERSION}"
      - "FFMPEG_VERSION=${FFMPEG_VERSION}"
      - "CFLAGS=${CFLAGS}"
    ports:
      - ${HTTP_ACCESS_PORT}:80
      - ${SSL_ACCESS_PORT}:443
      - ${RTMP_P1}:1935
      - ${SMB_TCP_PORT1}:139
      - ${SMB_TCP_PORT2}:445
      - ${SMB_UDP_PORT1}:137
      - ${SMB_UDP_PORT2}:138
      - ${PLEX_PORT}:32400
      - ${HTTP_SECONDARY}:8080
    volumes:
      - ./sites:/var/www/html
        # - ./ops/certs:/etc/letsencrypt/live
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/intranet/config
      - ./ops/logs:/var/log
      - ./util:/intranet/util
    networks:
      - home
      - ops
    labels:
      com.iwc.stack: "alpine, php, nginx, ffmpg, and rtmp services with support for xdebug, vnc and other passthrough ports"
      com.iwc.description: "Reverse proxy handling of DNS entries"
      com.iwc.type: "proxy"

  dnsmasqd:
    env_file:
      - ./.env
    image: ${DOCKER_ACCT}/intranet_dnsmasqd:${PROC_TYPE}-v${IWC_INTRANET_VERSION}
    #build:
      #context: ./dns/docker-dnsmasq
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: dnsmasq
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
    volumes:
      - ./config/webproc/webproc-dnsmasq.toml:/config/webproc/webproc-dnsmasq.toml
      - ./config/global/resolv.conf:/etc/resolv.conf
      - ./config/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./config:/intranet/config
      - ./ops/logs:/var/log
      - ./storage/ftp:/etc/dnsmasq/ftp
      - ./util:/intranet/util
    labels:
      com.iwc.stack: "alpine"
      com.iwc.description: "dnsmaq daemon as port 53 manager"
      com.iwc.type: "dns"
      com.iwc.context: "NET_ADMIN"
      com.iwc.network_mode: "host"
      com.iwc.notes: "This manages port 53 of the host (no port setting)"

  dnscryptd:
    env_file:
      - ./.env
    image: ${DOCKER_ACCT}/intranet_dnscrypt-proxy:${PROC_TYPE}-v${IWC_INTRANET_VERSION}
    #build:
      #context: ./dns/docker-dnscrypt
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    restart: unless-stopped
    container_name: dnscrypt
    ports:
      - ${DNSCRYPT_UDP}:53/udp
      - ${DNSCRYPT_TCP}:53/tcp
    depends_on:
      - dnsmasqd
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
    volumes:
      - ./config/webproc/webproc-dnscrypt.toml:/config/webproc/webproc-dnscrypt.toml
      - ./config/dnscrypt/dnscrypt.toml:/config/dnscrypt-proxy.toml
      - ./ops/logs:/var/log
      - ./config:/intranet/config
      - ./util:/intranet/util
    networks:
      - home
      - ops
    labels:
      com.iwc.stack: "alpine"
      com.iwc.description: "dnscrypt-proxy for encrypting dnsmasq traffic"
      com.iwc.type: "proxy"

  smbd:
   env_file:
     - ./.env
   image: ${DOCKER_ACCT}/intranet_smbd:${PROC_TYPE}-v${IWC_INTRANET_VERSION}
   build:
     context: ./storage/docker-samba
   deploy:
     mode: replicated
     replicas: 2
     restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s
   restart: unless-stopped
   container_name: smbd
   environment:
      - CERTS_DIR=/etc/letsencrypt/live
   volumes: 
     - ./storage/ftp:/media/samba/ftp
     - ./storage/docker-samba/shares:/media/samba
     - ./config/samba/smb.conf:/etc/samba/smb.conf
     - ./config:/intranet/config
     - ./ops/certs:/etc/letsencrypt/live
     - ./ops/logs:/var/log
     - ./util:/intranet/util
   ports:
     - "${SMB_UDP_PORT1}:137/udp"
     - "${SMB_UDP_PORT2}:138/udp"
     - "${SMB_TCP_PORT1}:139"
     - "${SMB_TCP_PORT2}:445"
   networks:
     - home
     - ops
   labels:
     com.iwc.stack: "alpine"
     com.iwc.description: "Samba access to shared volumes"
     com.iwc.type: "storage"

  rsync:
    env_file:
      - ./.env
    image: ${DOCKER_ACCT}/intranet_rsync:${PROC_TYPE}-v${IWC_INTRANET_VERSION}
    container_name: rsync
    build:
      context: ./storage/docker-rsync
    ports:
      - ${RSYNC_PORT}:873
      - ${SSH_PORT}:22
    environment:
      - CERT_DIR=${CERT_DIR}
    volumes:
      - .ssh/authorized_keys:/root/.ssh/authorized_keys
      - ./storage/ftp/public:/data/public
      - ./storage/ftp/public:/volume
      - ./ops/certs:/etc/letsencrypt/live
      - ./ops/logs:/var/log
      - ./config:/intranet/config
      - ./util:/intranet/util
    networks:
      - home
      - ops
    labels:
      com.iwc.stack: "debian"
      com.iwc.description: "rsync and ssh server access to shared volumes"
      com.iwc.type: "storage"

networks:
  ops:
    driver: bridge
  home:
    driver: bridge
