FROM jonmcquade/alpine-nginx-nodejs

COPY ./package.prod.json /
COPY ./public_build/ /build/ 
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./entrypoint /entrypoint

RUN mv /package.prod.json /package.json && \
    rm -f /build/app.js && \
    cd /build; ls -l

CMD sh ./entrypoint

 

