version: '3'
      
services:
  
  flightsearch:
    container_name: aspnetcore-react-redux
    image: jonmcquade/aspnetcore-react-redux:latest
    restart: on-failure:5
    tmpfs: 
      - /dotnetcorespa/Properties
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        aspenv: Production
        runtime: Release
        port: 3000
        sslPort: 3001
        verbosity: normal # q[uiet], m[inimal], n[ormal], d[etailed], or diag[nostic]
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "PORT=3000"
      - "SSL_PORT=3001"
      - "ASPNETCORE_URLS=http://*:3000;https://*:3001"
    ports:
     - "3000:3000"
     - "3001:3001"
